FROM web-kleber-dev
RUN apk update && apk add mailcap
RUN mv kleber/local_settings_prod_NOTUSE.py kleber/local_settings_prod.py
RUN mkdir /srv/static
RUN python manage.py collectstatic
CMD uwsgi --http "0.0.0.0:8000" --module kleber.wsgi --master --processes 4 --threads 2 --check-static /srv/static --mimefile /etc/mime.types