version: "3.8"
   
services:
  kleber-db:
    container_name: kleber-db
    restart: always
    image: postgres:9.6
    volumes:
      - /Users/takeshix/Projects/kleber/backups/db-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kleber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  kleber:
    container_name: kleber
    restart: always
    image: web-kleber-dev
    #build: .
    working_dir: /srv/kleber
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - kleber-db
    volumes:
      - /Users/takeshix/Projects/kleber/backups/uploads-dev:/srv/kleber/uploads
    ports:
      - "8000:8000"