# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KleberInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('shortcut', models.CharField(max_length=60, unique=True)),
                ('size', models.IntegerField()),
                ('mimetype', models.TextField()),
                ('mimetype_long', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lifetime', models.DateTimeField(blank=True, null=True)),
                ('burn_after_reading', models.BooleanField(default=False)),
                ('hits', models.IntegerField(default=0)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('kleberinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.KleberInput')),
                ('uploaded_file', models.FileField(default=None, upload_to='uploads/')),
                ('remove_meta', models.BooleanField(default=False)),
                ('remove_meta_message', models.TextField()),
                ('metadata', models.TextField()),
                ('checksum', models.TextField()),
                ('is_file', models.BooleanField(default=True)),
            ],
            bases=('web.kleberinput',),
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('kleberinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.KleberInput')),
                ('content', models.TextField()),
                ('lexer', models.TextField()),
                ('is_file', models.BooleanField(default=False)),
            ],
            bases=('web.kleberinput',),
        ),
        migrations.AddField(
            model_name='kleberinput',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
