# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_file',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='is_file',
        ),
        migrations.AddField(
            model_name='kleberinput',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
