# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170203_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='lexer',
        ),
        migrations.AddField(
            model_name='kleberinput',
            name='lexer',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
