# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170204_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='clean_checksum',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
