# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170304_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
