# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170304_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserConfig',
        ),
    ]
