# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170306_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invite',
            new_name='Voucher',
        ),
    ]
